---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgAc/9OFxtqyk4kkkch2HxGmjWFIscdDHmXJAW2tBH5DiHPzlM2tEO7OfSB5ake3HkuSy7s65OCNL2oOa0302Tbuh+aNfqIzE+YYKR88yKq/6kwP/vneLIULnCLCKu5OhdGARKhfEerYVJLIzr823O+9qjcfo6QJZs/a+JW5NIt5D6kPD7B0rOqVetJBTAyc34TF4uY2PgZTPrpC/Da70pmHCliC5WE+Oz3uKJm8avoXxj6fzFAsX1i6+JJ4/vYvfuP+PMYzDv+YZHFoxFEC49UsD+QycORHrMiwETUHQcGmOd8mnBCJwhuGST9P0Y7eqVHftLTdWVJs8cgKfUjARI6VXPUA4E6GYvvY1ZYgVrujyvvHqcvaaeRvVURg/Mpy4oeauLF0d3nJNe4x0oe/kNMajI4ZBKjjEuUS1Z8M25291pLR9ZzH6ILEX1bFMmpb4/yZEfH0kjAF6zuudl2oTuO5jIxmvaUDDAnWguP60s1/ntfSzuPztSvlkuqmqwD/u5ZkvHfU+2MJF6h33Z6Dkr/9Z4fQAZ9B1nieUMhq5lcWeqqLbrXqNAa3qfuZvfL9fYuVm9Gd1h4SAjiwbXCUeFQDzqcG9a04YZtcwA/dErDTQ7CJG7QlXb20FsRC/qFwKfuqE4+SBmIGAfnNApcYDbTV2mzOFJg4T7tHaFU9BF6Nd9Vq9PVa1g91PtO5BKq3pd9WtLMpR3FF31glNtt1uMOFXL6oJhqMgGK7
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
