apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:kwWxYxnWqBCbhZ8SOQgXhqiG0vFZCKozRA==,iv:2gbkeorb0sD1/crM5ScJ/6Of6CvNs4kA7PvGmovWkok=,tag:Hzawx1ztLYUAFxl2MfeYcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-19T07:38:56Z"
    mac: ENC[AES256_GCM,data:/e1ofNYMIN9KdKF8mZIY9J0L9xko7TrTS9DidTrbmCVUNYDU4zTKpN5NAPVLvOohVjyLs2g6PPbsU206TG1A1xvVHVi8T6LNzpayucwf8ycYoqWxFP24dQLgXlw4orc5EMA2Dc1skZ/hIbFsRNgSCuPkh0G48bNUJoDxR8xEhuQ=,iv:wSAQ1KLwuTofODRuGkPmfm0lS3m5NCkWHdJX8BL2TMQ=,tag:Y8ghz259a9rMmYjQF8P0Cw==,type:str]
    pgp:
        - created_at: "2023-10-19T07:38:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA+aDO1RBskfqAQv+ODcGxGwVOynetxatjiwBClaLxVofW5FJydYtapkF0yYJ
            KdAPtHeREANL8Qo5ZbiBX0y4WLYRRe7+X4HZdeHuGC4EHcH8VmuQFLNwnVSWX1HX
            5Rs1jMYauC/YJDu9cMobjDwsUCOhwBST2QOknQwUXuNhTjM/x+qR+ieSsgTfmykW
            53IZs7ruAOMHRlVr4bMaisLPS5fzmwVnExiQhLekLT3tQYyK6XWxjNV9kCHQ+pk0
            Xf0jdf9PpvfR6NsUzaDoJgnku9pRNxzcrpEi5V9y9eTPDJbTS/E4EEItSJC9T0Ae
            jkyIc/vX3u/R1gsVOE3NqKL/FMjs6s69fi0tz/1dpZhvYwdPY4Cia/vx0L0i19MF
            xpxicDMEs6BdLG7nL6YqfXNP2FYfYQJBJXsinVYBDuML0K2cohBA5jcGOkmjqWsK
            4uox+QwWy3ShqEe0pwX+JOs5Ona1wOLp2f6BJLdZwKue74TkIH9v8NyRPzSEflsS
            YNeZYVJiHBmkAsMFLwgz1GgBCQIQA8kFp57ctZGxp8Rms6K+b/imFQuzD/z46a01
            dTf8l0gOl3mEc7hJafhF/kO40dd3F/tQipiz5p/v4Yw+pM99IHbCscddzFj1YMEv
            q9QlcOc5XYbwX7clAJEKsjYOsIkkIHw+WA==
            =gZUz
            -----END PGP MESSAGE-----
          fp: A682996729F1A7BA
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
